'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number.isFinite(x)?x.toFixed(4):'—'; let rows=[],current=null;
const prediction=r=>$('seed').value==='ensemble'?Object.values(r.predictions).reduce((a,b)=>a+b,0)/Object.keys(r.predictions).length:r.predictions[$('seed').value];
const error=r=>Math.abs(prediction(r)-r.measured_score);
function rank(v){const ids=v.map((_,i)=>i).sort((a,b)=>v[a]-v[b]),r=[];let a=0;while(a<v.length){let b=a+1;while(b<v.length&&v[ids[b]]===v[ids[a]])b++;for(let j=a;j<b;j++)r[ids[j]]=(a+b-1)/2;a=b}return r}
function corr(x,y){if(x.length<2)return null; x=rank(x);y=rank(y);const avg=a=>a.reduce((s,v)=>s+v,0)/a.length,m=avg(x),n=avg(y),den=Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)*y.reduce((s,v)=>s+(v-n)**2,0));return den?x.reduce((s,v,i)=>s+(v-m)*(y[i]-n),0)/den:null}
function render(){const q=$('search').value.trim().toLowerCase();rows=DATA.records.filter(r=>r.task===$('task').value&&(!q||(r.name+' '+r.family+' '+Object.values(r.scopes).flatMap(s=>s.node_types).join(' ')).toLowerCase().includes(q))&&($('status').value==='all'||(r.measurements.every(m=>m.status==='completed')? 'completed':'failed')===$('status').value));rows.sort((a,b)=>({error:()=>error(b)-error(a),pred:()=>prediction(b)-prediction(a),actual:()=>b.measured_score-a.measured_score,name:()=>a.name.localeCompare(b.name)})[$('sort').value]());
 const n=rows.length,mae=n?rows.reduce((s,r)=>s+error(r),0)/n:null,rmse=n?Math.sqrt(rows.reduce((s,r)=>s+error(r)**2,0)/n):null;
 $('stats').innerHTML=[['当前筛选架构',n],['平均绝对误差 MAE',fmt(mae)],['均方根误差 RMSE',fmt(rmse)],['排序相关 Spearman',fmt(corr(rows.map(prediction),rows.map(r=>r.measured_score)))]].map(([k,v])=>`<div class="stat"><span>${k}</span><strong>${v}</strong></div>`).join('');
 $('count').textContent=n+' 个';$('list').innerHTML=rows.length?rows.map(r=>`<button type="button" class="row" data-id="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>误差 ${fmt(error(r))} · 实测 ${fmt(r.measured_score)}</small></button>`).join(''):'<p class="empty">没有匹配的架构</p>';
 $('list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.id));
 if(!rows.length){document.querySelector('.workspace').hidden=true;current=null;return}document.querySelector('.workspace').hidden=false;select(rows.some(r=>r.id===current?.id)?current.id:rows[0].id);
}
function select(id){const found=rows.find(r=>r.id===id);if(!found)return;current=found;const r=current,p=prediction(r);$('list').querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id))});
 $('name').textContent=r.name;$('resources').textContent=`${r.resources.parameters.toLocaleString()} 参数 · ${r.resources.stored_ops} 存储算子 · ${r.resources.expanded_ops} 展开算子`;
 $('download').href=r.graph_url;$('scope').innerHTML=Object.keys(r.scopes).sort((a,b)=>a==='root'?-1:b==='root'?1:a.localeCompare(b)).map(s=>`<option>${esc(s)}</option>`).join('');drawGraph();
 $('json').textContent='正在读取 GraphIR…'; fetch(r.graph_url).then(x=>{if(!x.ok)throw Error(x.status);return x.json()}).then(g=>{if(current?.id===r.id)$('json').textContent=JSON.stringify(g,null,2)}).catch(()=>{if(current?.id===r.id)$('json').textContent='无法读取架构文件，请使用上方 GraphIR 下载链接。'});$('provenance').textContent='使用冻结源码、原始生成种子和分层编号重建；家族标识及全部资源字段与历史记录一致。尚未取得远端原始图哈希。';$('hash').textContent='重建文件 SHA256: '+r.graph_sha256;
 $('scores').innerHTML=[['预测 score',p],['实测 score',r.measured_score],['绝对误差',error(r)]].map(([label,v])=>`<div class="score">${label}<b>${fmt(v)}</b></div>`).join('');$('bars').innerHTML=[['预测',p,''],['实测',r.measured_score,'actual']].map(([k,v,c])=>`<div class="barline"><span>${k}</span><div class="bartrack"><div class="bar ${c}" style="width:${v*100}%"></div></div></div>`).join('');
 $('predictions').innerHTML=Object.entries(r.predictions).map(([s,v])=>`<div class="seedrow"><span>种子 ${esc(s)} · epoch ${DATA.summaries.find(x=>x.task===r.task&&x.seed===s).best_epoch}</span><b>${fmt(v)}</b></div>`).join('');
 $('runs').innerHTML=r.measurements.map(m=>`<tr><td>${m.seed}</td><td>${m.status==='completed'?'完成':esc(m.status)}</td><td>${fmt(m.validation_nmse)}</td><td>${m.best_epoch??'—'}</td></tr>`).join('');$('raw').textContent=JSON.stringify(r.measurements,null,2);drawScatter();
 const params=new URLSearchParams({task:$('task').value,seed:$('seed').value,id:r.name});history.replaceState(null,'','#'+params);
}
function drawGraph(){if(!current)return;const scope=current.scopes[$('scope').value],positions={},levels={};scope.node_ids.forEach((id,i)=>{const depth=scope.stored_depth[i];(levels[depth]??=[]).push([id,scope.node_types[i]])});const maxcols=Math.max(...Object.values(levels).map(a=>a.length)),w=Math.max(420,maxcols*185+40),h=(Math.max(...scope.stored_depth)+1)*96+35;
 Object.entries(levels).forEach(([depth,ns])=>ns.forEach(([id,type],i)=>positions[id]={x:w/2+(i-(ns.length-1)/2)*185,y:25+Number(depth)*96,type}));
 let svg=`<svg role="img" aria-label="${esc(current.name)} ${esc($('scope').value)} 架构图" xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#8b9caf"/></marker></defs>`;
 scope.edges.forEach(e=>{const a=positions[e.source],b=positions[e.target];if(!a||!b)return;svg+=`<path d="M${a.x} ${a.y+49}C${a.x} ${(a.y+b.y+49)/2},${b.x} ${(a.y+b.y+49)/2},${b.x} ${b.y-3}" fill="none" stroke="#abb9c9" stroke-width="1.3" marker-end="url(#arrow)"><title>${esc(e.source)}:${esc(e.source_port)} → ${esc(e.target)}:${esc(e.target_port)} · ${esc(e.tensor?.shape?.join(' × ')||'')}</title></path>`});
 Object.entries(positions).forEach(([id,p])=>{const loop=['REPEAT','SCAN'].includes(p.type);svg+=`<g><rect x="${p.x-79}" y="${p.y}" width="158" height="49" rx="6" fill="${loop?'#e9efff':p.type==='PARAMETER'?'#f0edf8':'#ffffff'}" stroke="${loop?'#6485d3':'#c5d1df'}"/><text x="${p.x}" y="${p.y+19}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#60728b">${esc(id)}</text><text x="${p.x}" y="${p.y+37}" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="600" fill="#203753">${esc(p.type)}</text></g>`});$('graph').innerHTML=svg+'</svg>';
}
function drawScatter(){let svg='<svg viewBox="0 0 400 300" role="img" aria-label="预测与实测散点图"><path d="M38 16V264H380" fill="none" stroke="#b5c2d2"/><path d="M38 264L380 16" stroke="#adbdce" stroke-dasharray="5 5"/>';[0,.5,1].forEach(v=>{svg+=`<text x="${38+v*342}" y="284" text-anchor="middle" font-size="12" fill="#64768e">${v}</text><text x="28" y="${268-v*248}" text-anchor="end" font-size="12" fill="#64768e">${v}</text>`});rows.forEach(r=>svg+=`<circle tabindex="0" role="button" aria-label="查看 ${esc(r.name)}" data-id="${esc(r.id)}" cx="${38+r.measured_score*342}" cy="${264-prediction(r)*248}" r="${r===current?5:3.5}" fill="${r===current?'#d45726':'#2869c9'}" opacity="${r===current?1:.55}"><title>${esc(r.name)} · 预测 ${fmt(prediction(r))} / 实测 ${fmt(r.measured_score)}</title></circle>`);$('scatter').innerHTML=svg+'</svg>';$('scatter').querySelectorAll('circle').forEach(c=>{c.onclick=()=>select(c.dataset.id);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(c.dataset.id)}}})}
$('notice').textContent=DATA.note+' 当前数据：4,000 架构 / 固定学习率历史实验。';const init=new URLSearchParams(location.hash.slice(1));if(['adding','jena'].includes(init.get('task')))$('task').value=init.get('task');if(['101','202','303','ensemble'].includes(init.get('seed')))$('seed').value=init.get('seed');if(init.get('id'))current={id:$('task').value+':'+init.get('id')};['task','seed','status','sort'].forEach(id=>$(id).onchange=render);$('search').oninput=render;$('scope').onchange=drawGraph;render();
